version: "3.8"

name: "voting"

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=Springdata
    ports:
      - "3306:3306"